coverage:
        precision: 1
        range: 70...100

        status:
                project:
                        default:
                                enabled: yes
                                threshold: 1
                                if_not_found: success
                                if_no_updates: success

comment:
        behavior: new
