language: android

jdk:
  - openjdk7
  - openjdk8
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: hRICT/jbg/nUqpf3z1bA0/W5B18gG4tXcS1PknosyCJlDqTzqAoAxY8txwCDaIODXlRTr0Ttmo+JhzR2nvoP0ojMu++FJRtsB7Zk7sC9QPTJJBgVcMiV6GpzMEK/KCBN4Z/bVFnVCUWleEkysKpctYGCpUZodsjicA7CLU2bRSY3wvVF93HugPA00qZjY2o85F/pKH5m1liazo/bO3R1GWZ0qFnisqpFcaGWp0RFeh4GHG2n+h7vZmytE/wHuEg5iXrbb4lq6I4aDVeYOffpUcHp/u6fs2U1wzdNqN0krNcNQcHZI+NaRQzc0nJ3ntWdxJx+FkptBW5p1run1ynvY3y1qhT3F80qEwoLoM8z6jimvD5yJjhzFRDYyykZqNu7XqqYn88PpjUFHtghLBvJQ1WSMb7OmbMdExt/l1W/23FGWRKEcJHD8dw91pv6efZcVqT+JlweVtUiMz0XDEKdZDBjWZqhK4/wiNsIjsNeIocyKESKyzz6jg9p2qu8b8MTTR2hmVtOCJQmbhKl9uC4UVExqsK0w52LQfmtQ82BfsUU7OPMCULOCmnG195v9q0FmgGi7+IQpIm6HmL3iinNTNKFeN3atWz/EgAdmUo4cnjS5KIsf+Ko/IcbsuRLCufT3nnmKKN/JiuBPQ5RM4Eu4LnVils7G+78xbUtUa9q98c=
    - secure: LbWygLMrmjUdwuwgPYf8P2RGuzWC+eRgH4DsmZtsy1SvaE26EX4tlPxbrSJFD8qrDTcfrzpJjrIuQzMHC2vN7K592t7XXHFb6iIUocm3wEbjvQSoaHHpX6lLXFNhJSNabhEyhE10DiBfRn9tkXE7NbQjRgyzhb0tD8iNZY/q/xB++NU6ghAICZP/Bx8xuT8ioIIA9RmEgGZRq9Ym9sqpvlZ8Lx8vKXjQlBS8GXKgZcIwwlQRXh6ciRRim29Lsyp9pBrp2rOoTBEbm1vaozuzFuqUuhA/9mdaKGu2/H75vH3iQL3yKcm4Jgb8rAvfSpfaxTxAV3mfG4jYZA6NSyz7WIn9GppPrxnbHZhIMK+g8BbrWyHdRR3IG8LV4j/Ln05LA+0bbJee2stqOLQvRbuHCBqXN1JmsABC8VHJIN2PjLOblvcpV2cf++hq2xzTCSIjXaNt7MhOP/caFC5LnOUFv4JNt4J5KyKa78rl6O6W8IYcBdZtjHdwOPRcIkIHDcqi4kvcLQMt1cz3ZHMoQgc6Izpo3b3hMMuTSdKBbBSbY3towFtg/7XwDW4FXERVaPhs8Z5AYSUnusGlhq2wY0H0oV14HrliQO9i2Tuk2p8hlIRjQQZDzq15YGehWrI/tDpvurgNa9SYGcqxvBn+XPeS3OnTyvEypuG653Wxi/Mb/nQ=

android:
  components:
    - build-tools-20.0.0
    - android-16
  licenses:
    - android-sdk-license-5be876d5

sudo: required

branches:
  except:
    - gh-pages

notifications:
  slack:
    - secure: KTrEbtoFwNCHe3Xa+WVpyVMENu35Y+rml9Xs7XNtcjk6Ke//DvjGZTIUwuG9GWXmT+aDkLL4CaBUUhRapZdg7CUsBjIU5rusBSsOJEuAWUu0QcLDVRC1lxhSo8Ebcf8KxMtrFAW4h7psjGvDg3eBCj6vH5/+wUMS4lzgeDYoouhZUKETshKd7rrYCQy5qH4nmkoHFKQ5qJNFh/uVCyvQerEZnLOK6EHFfV5ZG9f74gt+3yNYJkQRBEvCccj7cpLUYQze42ZHyvQmqBg8AEad8stJQa4G6wVd186BXTkz03vVdtzivdLgHwcDS0NNkbd4OOiVBR0jX0EyiTAD83GYxX2tSMuumpqEDNGzZuCLdHPR+X2ZpWgHY7XB8ipafpSMMAaB0sxe+YTfjJduFiGcnPr1PcVOIY/sOWZZ4AM7jOR5ymFozQ5XlKcCZQJqrtm4cgQezmJzsTYqRZjmfp4H5VxpFN07qejOcTjKTN/n7nFpbH8LKsEflwhfN/MPHyA4iL9E00X2m3wp+jZLdj9lwjPyPhxRXynmGickvDHbLk7yYb+blO0b2fMYhnKHg1vJMxaB53iChzFv70IWW05O3n+eFH7FwVsboZBWofEmxPmat73HG2x3ViUbAwPEa/LZVAQ8Cw89mxiBZXVd1/3vyIQXWF3iaKdZrDGXIvtx6qY=

cache:
  directories:
    - $HOME/.m2
